### ISSUE TITLE
Errata in the README

### ISSUE THREAD

**Issue by VictorNS69** [FacultadInformatica-LinkedData/Curso2019-2020#193]
Some of the links in the actual README are not correct.

I wrote the erratas in the comments section in your last commit: https://github.com/FacultadInformatica-LinkedData/Curso2019-2020/commit/42e3ffa711fe5215b656a4052634751fee1f9dae#diff-04c6e90faac2675aa89e2176d2eec7d8R40

**Comment by ocorcho** [comment]
Fixed in 3eba76e630de516584c3eb61ee76c9953023c8cf
