### ISSUE TITLE
Una duda sobre elementos del grafo

### ISSUE THREAD

**Issue by FuchengUpm** [FacultadInformatica-LinkedData/Curso2019-2020#83]
`<rdf:Description rdf:about="#User10A">
	<hasName rdf:resource="#Pedro"/>
    </rdf:Description>```

Oye has puesto que tanto "Pedro" como el "29" y la fecha "2010-06-12T12:00:12" son recursos, pero
según el pdf son literales no ?

_Originally posted by @FuchengUpm in https://github.com/FacultadInformatica-LinkedData/Curso2019-2020/pull/81#issuecomment-531003967_

**Comment by ocorcho** [comment]
Sí, deben ser literales
